###
# アプリケーションのヘルスチェック
GET http://localhost:8080/v1/health

###
# ユーザーの新規登録
POST http://localhost:8080/v1/users/register

{
  "name": "ユーザー名",
  "email": "user@example.com",
  "password": "securepassword1",
  "profile": "プロフィール説明文",
  "skills": [
    {
      "evaluation": 10,
      "years": 3,
      "tag_name": "Go"
    },
    {
      "evaluation": 4,
      "years": 2,
      "tag_name": "JavaScript"
    }
  ],
  "careers": [
    {
      "detail": "ソフトウェアエンジニア",
      "start_year": 2018,
      "end_year": 2020
    },
    {
      "detail": "シニアソフトウェアエンジニア",
      "start_year": 2020,
      "end_year": 2022
    }
  ]
}

###
# ユーザーの新規登録
POST http://localhost:8080/v1/users/save

{
  "name": "新しいユーザー名",
  "email": "newuser@example.com",
  "password": "newSecurePassword123",
  "profile": "新しいプロフィール説明。技術者としての経験をさらに深め、チームでのコラボレーションを重視しています。",
  "skills": [
    {
      "evaluation": 5,
      "years": 4,
      "tag_name": "Python"
    },
    {
      "evaluation": 4,
      "years": 3,
      "tag_name": "React"
    },
    {
      "evaluation": 3,
      "years": 2,
      "tag_name": "Docker"
    }
  ],
  "careers": [
    {
      "detail": "フロントエンド開発者",
      "start_year": 2019,
      "end_year": 2021
    },
    {
      "detail": "バックエンド開発者",
      "start_year": 2021,
      "end_year": 2023
    },
    {
      "detail": "DevOps エンジニア",
      "start_year": 2023,
      "end_year": 2024
    }
  ]
}

###
# ユーザーの更新
POST http://localhost:8080/v1/users/update

{
  "user_id": "01HQJ1B15V28C9NZC4Z0H1JEKS",
  "name": "山田 太郎太郎",
  "email": "taro.yamada@example.com",
  "password": "newpassword123",
  "profile": "経験豊富なソフトウェアエンジニアです。",
  "skills": [
    {
      "skill_id": "skill01dfa",
      "tag_id": "01HQJ18F981Y2R7B4TBP0J8ACX",
      "evaluation": 5,
      "years": 1
    },
    {
      "skill_id": "skill02dfa",
      "tag_id": "01HQJ18F981Y2R7B4TBP0J8ACX",
      "evaluation": 4,
      "years": 5
    }
  ],
  "careers": [
    {
      "career_id": "career0121",
      "detail": "ソフトウェア開発者として5年間勤務。",
      "start_year": 2015,
      "end_year": 2020
    },
    {
      "career_id": "career02ffa",
      "detail": "プロジェクトマネージャーとして3年間勤務。",
      "start_year": 2020,
      "end_year": 2023
    }
  ]
}