// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package dbgen

import (
	"time"
)

type Career struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Detail    string    `json:"detail"`
	StartYear int32     `json:"start_year"`
	EndYear   int32     `json:"end_year"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Skill struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	TagID      string    `json:"tag_id"`
	Evaluation int32     `json:"evaluation"`
	Years      int32     `json:"years"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Tag struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Name      string    `json:"name"`
	Profile   string    `json:"profile"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
