// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package dbgen

import (
	"context"
)

type Querier interface {
	FindByID(ctx context.Context, id string) (User, error)
	FindByName(ctx context.Context, name string) (User, error)
	FindByNames(ctx context.Context, names []string) ([]FindByNamesRow, error)
	FindCareersByUserID(ctx context.Context, userID string) ([]Career, error)
	FindSkillsByUserID(ctx context.Context, userID string) ([]Skill, error)
	UpsertCareer(ctx context.Context, arg UpsertCareerParams) error
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) error
	UpsertTag(ctx context.Context, arg UpsertTagParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
