// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: skill.sql

package dbgen

import (
	"context"
)

const upsertSkill = `-- name: UpsertSkill :exec
INSERT INTO skills (id,
                    user_id,
                    tag_id,
                    evaluation,
                    years,
                    created_at,
                    updated_at)
VALUES (?,
        ?,
        ?,
        ?,
        ?,
        NOW(),
        NOW()) ON DUPLICATE KEY
UPDATE
    user_id = ?,
    tag_id = ?,
    evaluation = ?,
    years = ?,
    updated_at = NOW()
`

type UpsertSkillParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	TagID      string `json:"tag_id"`
	Evaluation int32  `json:"evaluation"`
	Years      int32  `json:"years"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkill,
		arg.ID,
		arg.UserID,
		arg.TagID,
		arg.Evaluation,
		arg.Years,
		arg.UserID,
		arg.TagID,
		arg.Evaluation,
		arg.Years,
	)
	return err
}
